// 500 mots les plus utilisés du Coran
// DONNÉES — Vocabulaire coranique (500 mots les plus utilisés)
// ═══════════════════════════════════════════════════════
const VOCAB = [
  {id:1,ar:"اللَّهُ",tr:"Allāhu",fr:"Allah",freq:2699,cat:"essentiel"},
  {id:2,ar:"رَبِّ",tr:"rabbi",fr:"Seigneur (mon)",freq:980,cat:"essentiel"},
  {id:3,ar:"قَالَ",tr:"qāla",fr:"Il dit",freq:529,cat:"verbe"},
  {id:4,ar:"إِنَّ",tr:"inna",fr:"Certes / vraiment",freq:1709,cat:"particule"},
  {id:5,ar:"مَا",tr:"mā",fr:"ce qui / pas (nég.)",freq:1598,cat:"particule"},
  {id:6,ar:"لَا",tr:"lā",fr:"non / ne...pas",freq:1403,cat:"particule"},
  {id:7,ar:"مِنْ",tr:"min",fr:"de / parmi",freq:2764,cat:"préposition"},
  {id:8,ar:"فِي",tr:"fī",fr:"dans / en",freq:1711,cat:"préposition"},
  {id:9,ar:"عَلَى",tr:"ʿalā",fr:"sur / contre",freq:1244,cat:"préposition"},
  {id:10,ar:"إِلَى",tr:"ilā",fr:"vers / jusqu'à",freq:742,cat:"préposition"},
  {id:11,ar:"الَّذِي",tr:"alladhī",fr:"celui qui",freq:1470,cat:"relatif"},
  {id:12,ar:"هُوَ",tr:"huwa",fr:"il / lui",freq:604,cat:"pronom"},
  {id:13,ar:"كَانَ",tr:"kāna",fr:"il était / a été",freq:1358,cat:"verbe"},
  {id:14,ar:"وَ",tr:"wa",fr:"et",freq:49248,cat:"particule"},
  {id:15,ar:"أَنَّ",tr:"anna",fr:"que (conjonction)",freq:1030,cat:"particule"},
  {id:16,ar:"لَهُمْ",tr:"lahum",fr:"pour eux / à eux",freq:817,cat:"pronom"},
  {id:17,ar:"يَوْمَ",tr:"yawma",fr:"le jour (où)",freq:405,cat:"temps"},
  {id:18,ar:"آمَنُوا",tr:"āmanū",fr:"ils ont cru",freq:258,cat:"verbe"},
  {id:19,ar:"النَّاسِ",tr:"n-nāsi",fr:"gens / humains",freq:241,cat:"nom"},
  {id:20,ar:"الْأَرْضِ",tr:"al-arḍi",fr:"la terre",freq:461,cat:"nom"},
  {id:21,ar:"السَّمَاوَاتِ",tr:"as-samāwāti",fr:"les cieux",freq:189,cat:"nom"},
  {id:22,ar:"رَحِيمٌ",tr:"raḥīmun",fr:"Très Miséricordieux",freq:115,cat:"attribut"},
  {id:23,ar:"الرَّحْمَانُ",tr:"ar-raḥmānu",fr:"Tout Miséricordieux",freq:57,cat:"attribut"},
  {id:24,ar:"عَلِيمٌ",tr:"ʿalīmun",fr:"Omniscient",freq:157,cat:"attribut"},
  {id:25,ar:"عَظِيمٌ",tr:"ʿaẓīmun",fr:"Immense / Grand",freq:108,cat:"attribut"},
  {id:26,ar:"حَكِيمٌ",tr:"ḥakīmun",fr:"Sage",freq:97,cat:"attribut"},
  {id:27,ar:"قَدِيرٌ",tr:"qadīrun",fr:"Puissant",freq:45,cat:"attribut"},
  {id:28,ar:"سَبِيلِ",tr:"sabīli",fr:"voie / chemin",freq:166,cat:"nom"},
  {id:29,ar:"نَفْسَ",tr:"nafsa",fr:"âme / soi-même",freq:295,cat:"nom"},
  {id:30,ar:"قُلْ",tr:"qul",fr:"Dis !",freq:332,cat:"verbe"},
  {id:31,ar:"كِتَابِ",tr:"kitābi",fr:"livre / écrit",freq:319,cat:"nom"},
  {id:32,ar:"حَقِّ",tr:"ḥaqqi",fr:"vérité / droit",freq:287,cat:"nom"},
  {id:33,ar:"نُورَ",tr:"nūra",fr:"lumière",freq:49,cat:"nom"},
  {id:34,ar:"قَلْبِ",tr:"qalbi",fr:"cœur",freq:132,cat:"nom"},
  {id:35,ar:"جَنَّةِ",tr:"jannati",fr:"paradis / jardin",freq:147,cat:"nom"},
  {id:36,ar:"نَارِ",tr:"nāri",fr:"feu / enfer",freq:145,cat:"nom"},
  {id:37,ar:"عَمِلَ",tr:"ʿamila",fr:"il a fait / oeuvré",freq:104,cat:"verbe"},
  {id:38,ar:"عِلْمِ",tr:"ʿilmi",fr:"science / connaissance",freq:105,cat:"nom"},
  {id:39,ar:"الصَّلَاةَ",tr:"aṣ-ṣalāta",fr:"la prière",freq:99,cat:"nom"},
  {id:40,ar:"رَسُولُ",tr:"rasūlu",fr:"messager / prophète",freq:332,cat:"nom"},
  {id:41,ar:"آيَاتِ",tr:"āyāti",fr:"signes / versets",freq:382,cat:"nom"},
  {id:42,ar:"مُؤْمِنُونَ",tr:"muʾminūna",fr:"croyants",freq:182,cat:"nom"},
  {id:43,ar:"ظَالِمُونَ",tr:"ẓālimūna",fr:"injustes",freq:94,cat:"nom"},
  {id:44,ar:"مُتَّقِينَ",tr:"muttaqīna",fr:"pieux / craignant Allah",freq:55,cat:"nom"},
  {id:45,ar:"شَيْءٍ",tr:"shayʾin",fr:"chose",freq:519,cat:"nom"},
  {id:46,ar:"خَيْرٌ",tr:"khayrun",fr:"bien / meilleur",freq:199,cat:"nom"},
  {id:47,ar:"كَبِيرٌ",tr:"kabīrun",fr:"grand / important",freq:73,cat:"adjectif"},
  {id:48,ar:"صَغِيرٌ",tr:"ṣaghīrun",fr:"petit",freq:14,cat:"adjectif"},
  {id:49,ar:"حَمْدُ",tr:"ḥamdu",fr:"louange",freq:42,cat:"nom"},
  {id:50,ar:"صِرَاطَ",tr:"ṣirāṭa",fr:"chemin droit",freq:45,cat:"nom"},
  {id:51,ar:"تَوْبَةَ",tr:"tawbata",fr:"repentir",freq:88,cat:"nom"},
  {id:52,ar:"رَحْمَةَ",tr:"raḥmata",fr:"miséricorde",freq:114,cat:"nom"},
  {id:53,ar:"نِعْمَةَ",tr:"niʿmata",fr:"bienfait / grâce",freq:66,cat:"nom"},
  {id:54,ar:"أَمْرَ",tr:"amra",fr:"ordre / affaire",freq:264,cat:"nom"},
  {id:55,ar:"قَوْمَ",tr:"qawma",fr:"peuple / nation",freq:383,cat:"nom"},
  {id:56,ar:"مُوسَى",tr:"mūsā",fr:"Moïse",freq:136,cat:"nom propre"},
  {id:57,ar:"إِبْرَاهِيمَ",tr:"ibrāhīm",fr:"Abraham",freq:69,cat:"nom propre"},
  {id:58,ar:"عِيسَى",tr:"ʿīsā",fr:"Jésus",freq:25,cat:"nom propre"},
  {id:59,ar:"مَلَائِكَةِ",tr:"malāʾikati",fr:"anges",freq:68,cat:"nom"},
  {id:60,ar:"شَيْطَانِ",tr:"shayṭāni",fr:"Satan",freq:88,cat:"nom"},
  {id:61,ar:"آخِرَةِ",tr:"ākhirati",fr:"au-delà",freq:115,cat:"nom"},
  {id:62,ar:"الدُّنْيَا",tr:"ad-dunyā",fr:"monde ici-bas",freq:115,cat:"nom"},
  {id:63,ar:"مَوْتِ",tr:"mawti",fr:"mort",freq:56,cat:"nom"},
  {id:64,ar:"حَيَاةِ",tr:"ḥayāti",fr:"vie",freq:71,cat:"nom"},
  {id:65,ar:"عَذَابِ",tr:"ʿadhābi",fr:"châtiment",freq:322,cat:"nom"},
  {id:66,ar:"ثَوَابِ",tr:"thawābi",fr:"récompense",freq:7,cat:"nom"},
  {id:67,ar:"أَجْرَ",tr:"ajra",fr:"salaire / rétribution",freq:107,cat:"nom"},
  {id:68,ar:"فَضْلِ",tr:"faḍli",fr:"faveur / grâce",freq:87,cat:"nom"},
  {id:69,ar:"حُكْمَ",tr:"ḥukma",fr:"jugement",freq:76,cat:"nom"},
  {id:70,ar:"صَبْرِ",tr:"ṣabri",fr:"patience",freq:90,cat:"nom"},
  {id:71,ar:"شُكْرِ",tr:"shukri",fr:"gratitude",freq:17,cat:"nom"},
  {id:72,ar:"إِيمَانِ",tr:"īmāni",fr:"foi / croyance",freq:45,cat:"nom"},
  {id:73,ar:"تَقْوَى",tr:"taqwā",fr:"piété",freq:41,cat:"nom"},
  {id:74,ar:"هُدًى",tr:"hudan",fr:"guidance",freq:95,cat:"nom"},
  {id:75,ar:"ضَلَالَ",tr:"ḍalāla",fr:"égarement",freq:34,cat:"nom"},
  {id:76,ar:"رَزَقَ",tr:"razaqa",fr:"Il a pourvu",freq:123,cat:"verbe"},
  {id:77,ar:"خَلَقَ",tr:"khalaqa",fr:"Il a créé",freq:85,cat:"verbe"},
  {id:78,ar:"أَرْسَلَ",tr:"arsala",fr:"Il a envoyé",freq:77,cat:"verbe"},
  {id:79,ar:"أَنزَلَ",tr:"anzala",fr:"Il a fait descendre",freq:97,cat:"verbe"},
  {id:80,ar:"جَعَلَ",tr:"jaʿala",fr:"Il a établi",freq:345,cat:"verbe"},
  {id:81,ar:"دَعَا",tr:"daʿā",fr:"Il a invoqué",freq:111,cat:"verbe"},
  {id:82,ar:"كَفَرَ",tr:"kafara",fr:"Il a mécru",freq:138,cat:"verbe"},
  {id:83,ar:"ظَلَمَ",tr:"ẓalama",fr:"Il a opprimé",freq:96,cat:"verbe"},
  {id:84,ar:"عَلِمَ",tr:"ʿalima",fr:"Il a su / connu",freq:382,cat:"verbe"},
  {id:85,ar:"سَمِعَ",tr:"samiʿa",fr:"Il a entendu",freq:185,cat:"verbe"},
  {id:86,ar:"يَدَ",tr:"yada",fr:"main",freq:120,cat:"nom"},
  {id:87,ar:"وَجْهَ",tr:"wajha",fr:"visage / face",freq:72,cat:"nom"},
  {id:88,ar:"عَقْلَ",tr:"ʿaqla",fr:"raison / intelligence",freq:49,cat:"nom"},
  {id:89,ar:"بَيْتِ",tr:"bayti",fr:"maison",freq:72,cat:"nom"},
  {id:90,ar:"أَهْلَ",tr:"ahla",fr:"famille / gens de",freq:127,cat:"nom"},
  {id:91,ar:"وَلَدَ",tr:"walada",fr:"enfant / fils",freq:36,cat:"nom"},
  {id:92,ar:"أَبٍ",tr:"abi",fr:"père",freq:120,cat:"nom"},
  {id:93,ar:"أُمَّةَ",tr:"ummata",fr:"communauté / nation",freq:64,cat:"nom"},
  {id:94,ar:"دِينِ",tr:"dīni",fr:"religion / jugement",freq:92,cat:"nom"},
  {id:95,ar:"إِسْلَامِ",tr:"islāmi",fr:"Islam / soumission",freq:8,cat:"nom"},
  {id:96,ar:"كُلِّ",tr:"kulli",fr:"tout / chaque",freq:654,cat:"particule"},
  {id:97,ar:"إِذَا",tr:"idhā",fr:"quand / lorsque",freq:408,cat:"particule"},
  {id:98,ar:"إِلَّا",tr:"illā",fr:"sauf / sinon",freq:659,cat:"particule"},
  {id:99,ar:"لَكِنَّ",tr:"lākinna",fr:"mais / cependant",freq:23,cat:"particule"},
  {id:100,ar:"حَتَّى",tr:"ḥattā",fr:"jusqu'à / même",freq:249,cat:"particule"},
  {id:101,ar:"لَعَلَّ",tr:"laʿalla",fr:"peut-être / afin que",freq:129,cat:"particule"},
  {id:102,ar:"هَلْ",tr:"hal",fr:"est-ce que ?",freq:181,cat:"particule"},
  {id:103,ar:"أَمْ",tr:"am",fr:"ou bien",freq:160,cat:"particule"},
  {id:104,ar:"ثُمَّ",tr:"thumma",fr:"puis / ensuite",freq:337,cat:"particule"},
  {id:105,ar:"بَعْدَ",tr:"baʿda",fr:"après",freq:159,cat:"préposition"},
  {id:106,ar:"قَبْلَ",tr:"qabla",fr:"avant",freq:154,cat:"préposition"},
  {id:107,ar:"عِنْدَ",tr:"ʿinda",fr:"auprès de / chez",freq:192,cat:"préposition"},
  {id:108,ar:"مَعَ",tr:"maʿa",fr:"avec / en compagnie de",freq:168,cat:"préposition"},
  {id:109,ar:"بَيْنَ",tr:"bayna",fr:"entre",freq:186,cat:"préposition"},
  {id:110,ar:"فَوْقَ",tr:"fawqa",fr:"au-dessus de",freq:22,cat:"préposition"},
  {id:111,ar:"تَحْتَ",tr:"taḥta",fr:"en-dessous de",freq:16,cat:"préposition"},
  {id:112,ar:"أَمَامَ",tr:"amāma",fr:"devant",freq:4,cat:"préposition"},
  {id:113,ar:"خَلْفَ",tr:"khalfa",fr:"derrière",freq:6,cat:"préposition"},
  {id:114,ar:"كَيْفَ",tr:"kayfa",fr:"comment",freq:42,cat:"particule"},
  {id:115,ar:"مَنْ",tr:"man",fr:"qui / celui qui",freq:651,cat:"pronom"},
  {id:116,ar:"هُمْ",tr:"hum",fr:"eux / ils",freq:419,cat:"pronom"},
  {id:117,ar:"هِيَ",tr:"hiya",fr:"elle",freq:186,cat:"pronom"},
  {id:118,ar:"نَحْنُ",tr:"naḥnu",fr:"nous",freq:64,cat:"pronom"},
  {id:119,ar:"أَنْتَ",tr:"anta",fr:"tu / toi (masc.)",freq:112,cat:"pronom"},
  {id:120,ar:"أَنَا",tr:"anā",fr:"je / moi",freq:65,cat:"pronom"},
  {id:121,ar:"يَوْمِ الْقِيَامَةِ",tr:"yawmi l-qiyāma",fr:"Jour du Jugement",freq:70,cat:"expression"},
  {id:122,ar:"الْقِيَامَةِ",tr:"al-qiyāmati",fr:"la Résurrection",freq:70,cat:"nom"},
  {id:123,ar:"جَهَنَّمَ",tr:"jahannama",fr:"Géhenne / Enfer",freq:77,cat:"nom"},
  {id:124,ar:"الْجَنَّةَ",tr:"al-jannata",fr:"le Paradis",freq:73,cat:"nom"},
  {id:125,ar:"مَلَكَ",tr:"malaka",fr:"ange / roi",freq:88,cat:"nom"},
  {id:126,ar:"نَبِيَّ",tr:"nabiyya",fr:"prophète",freq:75,cat:"nom"},
  {id:127,ar:"صَادِقِينَ",tr:"ṣādiqīna",fr:"véridiques / sincères",freq:24,cat:"nom"},
  {id:128,ar:"صَالِحِينَ",tr:"ṣāliḥīna",fr:"vertueux / justes",freq:43,cat:"nom"},
  {id:129,ar:"الصَّابِرِينَ",tr:"aṣ-ṣābirīna",fr:"les patients / endurants",freq:16,cat:"nom"},
  {id:130,ar:"الْكَافِرِينَ",tr:"al-kāfirīna",fr:"les mécréants",freq:93,cat:"nom"},
  {id:131,ar:"الْمُنَافِقِينَ",tr:"al-munāfiqīna",fr:"les hypocrites",freq:27,cat:"nom"},
  {id:132,ar:"الْمُشْرِكِينَ",tr:"al-mushrikīna",fr:"les associateurs",freq:36,cat:"nom"},
  {id:133,ar:"الظَّالِمِينَ",tr:"aẓ-ẓālimīna",fr:"les injustes",freq:97,cat:"nom"},
  {id:134,ar:"الْمُؤْمِنِينَ",tr:"al-muʾminīna",fr:"les croyants",freq:167,cat:"nom"},
  {id:135,ar:"الْفَاسِقِينَ",tr:"al-fāsiqīna",fr:"les pervers",freq:34,cat:"nom"},
  {id:136,ar:"قُرْآنَ",tr:"qurʾāna",fr:"Coran",freq:70,cat:"nom"},
  {id:137,ar:"تَوْرَاةَ",tr:"tawrāta",fr:"Torah",freq:18,cat:"nom"},
  {id:138,ar:"إِنجِيلَ",tr:"injīla",fr:"Évangile",freq:12,cat:"nom"},
  {id:139,ar:"سُورَةَ",tr:"sūrata",fr:"sourate",freq:8,cat:"nom"},
  {id:140,ar:"آيَةَ",tr:"āyata",fr:"verset / signe",freq:382,cat:"nom"},
  {id:141,ar:"بِسْمِ",tr:"bismi",fr:"au nom de",freq:114,cat:"expression"},
  {id:142,ar:"الْحَمْدُ لِلَّهِ",tr:"al-ḥamdu lillāh",fr:"Louange à Allah",freq:26,cat:"expression"},
  {id:143,ar:"سُبْحَانَ",tr:"subḥāna",fr:"Gloire à / Louange à",freq:41,cat:"verbe"},
  {id:144,ar:"تَبَارَكَ",tr:"tabāraka",fr:"Béni soit",freq:9,cat:"verbe"},
  {id:145,ar:"أَعُوذُ",tr:"aʿūdhu",fr:"je cherche refuge",freq:11,cat:"verbe"},
  {id:146,ar:"فَسُبْحَانَ",tr:"fa-subḥāna",fr:"Gloire donc à",freq:7,cat:"verbe"},
  {id:147,ar:"الصَّادِقُ",tr:"aṣ-ṣādiq",fr:"le Véridique",freq:5,cat:"attribut"},
  {id:148,ar:"الْحَكِيمُ",tr:"al-ḥakīm",fr:"le Sage",freq:97,cat:"attribut"},
  {id:149,ar:"الْعَزِيزُ",tr:"al-ʿazīz",fr:"le Tout-Puissant",freq:92,cat:"attribut"},
  {id:150,ar:"الْغَفُورُ",tr:"al-ghafūr",fr:"le Très Pardonneur",freq:91,cat:"attribut"},
  {id:151,ar:"الْوَدُودُ",tr:"al-wadūd",fr:"le Très Aimant",freq:2,cat:"attribut"},
  {id:152,ar:"الْكَرِيمُ",tr:"al-karīm",fr:"le Généreux",freq:2,cat:"attribut"},
  {id:153,ar:"الْعَلِيُّ",tr:"al-ʿaliyy",fr:"le Très Haut",freq:8,cat:"attribut"},
  {id:154,ar:"الْقَوِيُّ",tr:"al-qawiyy",fr:"le Fort",freq:9,cat:"attribut"},
  {id:155,ar:"السَّمِيعُ",tr:"as-samīʿ",fr:"l'Audient",freq:47,cat:"attribut"},
  {id:156,ar:"الْبَصِيرُ",tr:"al-baṣīr",fr:"le Clairvoyant",freq:42,cat:"attribut"},
  {id:157,ar:"الرَّحِيمُ",tr:"ar-raḥīm",fr:"le Très Miséricordieux",freq:115,cat:"attribut"},
  {id:158,ar:"الرَّحْمَانُ",tr:"ar-raḥmān",fr:"le Tout Miséricordieux",freq:57,cat:"attribut"},
  {id:159,ar:"الْقَهَّارُ",tr:"al-qahhār",fr:"le Dominateur",freq:6,cat:"attribut"},
  {id:160,ar:"الْوَاحِدُ",tr:"al-wāḥid",fr:"l'Unique",freq:22,cat:"attribut"},
  {id:161,ar:"الْأَحَدُ",tr:"al-aḥad",fr:"l'Un / l'Unique",freq:2,cat:"attribut"},
  {id:162,ar:"الصَّمَدُ",tr:"aṣ-ṣamad",fr:"le Seul imploré",freq:1,cat:"attribut"},
  {id:163,ar:"الْخَالِقُ",tr:"al-khāliq",fr:"le Créateur",freq:8,cat:"attribut"},
  {id:164,ar:"الرَّازِقُ",tr:"ar-rāziq",fr:"le Pourvoyeur",freq:6,cat:"attribut"},
  {id:165,ar:"الْفَتَّاحُ",tr:"al-fattāḥ",fr:"le Juge suprême",freq:1,cat:"attribut"},
  {id:166,ar:"الْعَلِيمُ",tr:"al-ʿalīm",fr:"l'Omniscient",freq:157,cat:"attribut"},
  {id:167,ar:"الْقَدِيرُ",tr:"al-qadīr",fr:"l'Omnipotent",freq:45,cat:"attribut"},
  {id:168,ar:"التَّوَّابُ",tr:"at-tawwāb",fr:"le Grand Repentant",freq:11,cat:"attribut"},
  {id:169,ar:"الْغَنِيُّ",tr:"al-ghaniyy",fr:"le Riche absolu",freq:18,cat:"attribut"},
  {id:170,ar:"الْحَمِيدُ",tr:"al-ḥamīd",fr:"le Digne de louange",freq:17,cat:"attribut"},
  {id:171,ar:"سُبْحَانَهُ",tr:"subḥānahu",fr:"Gloire à Lui",freq:41,cat:"expression"},
  {id:172,ar:"أَلَا",tr:"alā",fr:"non ! / certes !",freq:32,cat:"particule"},
  {id:173,ar:"كَذَلِكَ",tr:"kadhālika",fr:"ainsi / de même",freq:162,cat:"particule"},
  {id:174,ar:"إِنَّمَا",tr:"innamā",fr:"seulement / ce n'est que",freq:163,cat:"particule"},
  {id:175,ar:"لَمَّا",tr:"lammā",fr:"quand / lorsque",freq:68,cat:"particule"},
  {id:176,ar:"لَيْسَ",tr:"laysa",fr:"n'est pas / il n'y a pas",freq:85,cat:"verbe"},
  {id:177,ar:"يَعْلَمُ",tr:"yaʿlamu",fr:"il sait / connaît",freq:178,cat:"verbe"},
  {id:178,ar:"يَرَى",tr:"yarā",fr:"il voit",freq:46,cat:"verbe"},
  {id:179,ar:"يَشَاءُ",tr:"yashāʾu",fr:"il veut / permet",freq:148,cat:"verbe"},
  {id:180,ar:"يَعْبُدُونَ",tr:"yaʿbudūna",fr:"ils adorent",freq:32,cat:"verbe"},
  {id:181,ar:"يُؤْمِنُونَ",tr:"yuʾminūna",fr:"ils croient",freq:162,cat:"verbe"},
  {id:182,ar:"يَعْمَلُونَ",tr:"yaʿmalūna",fr:"ils font / oeuvrent",freq:101,cat:"verbe"},
  {id:183,ar:"يَتَّقُونَ",tr:"yattaqūna",fr:"ils craignent Allah",freq:42,cat:"verbe"},
  {id:184,ar:"يَكْفُرُونَ",tr:"yakfurūna",fr:"ils mécroyent",freq:35,cat:"verbe"},
  {id:185,ar:"يَفْعَلُونَ",tr:"yafʿalūna",fr:"ils font / agissent",freq:22,cat:"verbe"},
  {id:186,ar:"يَتَوَكَّلُونَ",tr:"yatawakkalūna",fr:"ils se confient à Allah",freq:14,cat:"verbe"},
  {id:187,ar:"يَسْتَغْفِرُونَ",tr:"yastaghfirūna",fr:"ils demandent pardon",freq:9,cat:"verbe"},
  {id:188,ar:"يُسَبِّحُونَ",tr:"yusabbiḥūna",fr:"ils glorifient",freq:11,cat:"verbe"},
  {id:189,ar:"يُكَذِّبُونَ",tr:"yukadhdhibūna",fr:"ils traitent de mensonge",freq:54,cat:"verbe"},
  {id:190,ar:"يَسْجُدُونَ",tr:"yasjudūna",fr:"ils se prosternent",freq:13,cat:"verbe"},
  {id:191,ar:"فَأَقِيمُوا",tr:"fa-aqīmū",fr:"établissez donc (la prière)",freq:8,cat:"verbe"},
  {id:192,ar:"آتُوا الزَّكَاةَ",tr:"ātū az-zakāta",fr:"acquittez la zakāt",freq:32,cat:"expression"},
  {id:193,ar:"الزَّكَاةَ",tr:"az-zakāta",fr:"la zakāt / aumône",freq:32,cat:"nom"},
  {id:194,ar:"الصِّيَامَ",tr:"aṣ-ṣiyāma",fr:"le jeûne",freq:2,cat:"nom"},
  {id:195,ar:"الْحَجَّ",tr:"al-ḥajj",fr:"le pèlerinage",freq:10,cat:"nom"},
  {id:196,ar:"الشَّهَادَةَ",tr:"ash-shahādata",fr:"le témoignage / martyre",freq:19,cat:"nom"},
  {id:197,ar:"الْجِهَادَ",tr:"al-jihāda",fr:"l'effort / la lutte",freq:35,cat:"nom"},
  {id:198,ar:"التَّسْبِيحَ",tr:"at-tasbīḥa",fr:"la glorification",freq:29,cat:"nom"},
  {id:199,ar:"الذِّكْرَ",tr:"adh-dhikra",fr:"le rappel / le souvenir",freq:60,cat:"nom"},
  {id:200,ar:"التَّفَكُّرَ",tr:"at-tafakkura",fr:"la réflexion",freq:8,cat:"nom"},
  {id:201,ar:"وَقْتِ",tr:"waqti",fr:"temps / moment",freq:17,cat:"nom"},
  {id:202,ar:"لَيْلِ",tr:"layli",fr:"nuit",freq:92,cat:"nom"},
  {id:203,ar:"نَهَارِ",tr:"nahāri",fr:"jour / journée",freq:57,cat:"nom"},
  {id:204,ar:"شَمْسِ",tr:"shamsi",fr:"soleil",freq:33,cat:"nom"},
  {id:205,ar:"قَمَرِ",tr:"qamari",fr:"lune",freq:27,cat:"nom"},
  {id:206,ar:"نُجُومِ",tr:"nujūmi",fr:"étoiles",freq:13,cat:"nom"},
  {id:207,ar:"مَاءِ",tr:"māʾi",fr:"eau",freq:63,cat:"nom"},
  {id:208,ar:"نَارٍ",tr:"nārin",fr:"feu",freq:145,cat:"nom"},
  {id:209,ar:"تُرَابِ",tr:"turābi",fr:"poussière / terre",freq:17,cat:"nom"},
  {id:210,ar:"رِيحِ",tr:"rīḥi",fr:"vent",freq:29,cat:"nom"},
  {id:211,ar:"سَحَابِ",tr:"saḥābi",fr:"nuages",freq:8,cat:"nom"},
  {id:212,ar:"مَطَرِ",tr:"maṭari",fr:"pluie",freq:7,cat:"nom"},
  {id:213,ar:"بَحْرِ",tr:"baḥri",fr:"mer / océan",freq:41,cat:"nom"},
  {id:214,ar:"نَهْرِ",tr:"nahri",fr:"fleuve / rivière",freq:13,cat:"nom"},
  {id:215,ar:"جَبَلِ",tr:"jabali",fr:"montagne",freq:39,cat:"nom"},
  {id:216,ar:"شَجَرَةِ",tr:"shajaratin",fr:"arbre",freq:26,cat:"nom"},
  {id:217,ar:"زَرْعِ",tr:"zarʿi",fr:"semence / culture",freq:15,cat:"nom"},
  {id:218,ar:"ثَمَرِ",tr:"thamari",fr:"fruit",freq:22,cat:"nom"},
  {id:219,ar:"حَيَوَانِ",tr:"ḥayawāni",fr:"animal / vie",freq:1,cat:"nom"},
  {id:220,ar:"إِنسَانِ",tr:"insāni",fr:"être humain",freq:65,cat:"nom"},
  {id:221,ar:"بَشَرِ",tr:"bashari",fr:"être humain / humanité",freq:37,cat:"nom"},
  {id:222,ar:"رُوحِ",tr:"rūḥi",fr:"esprit / souffle",freq:21,cat:"nom"},
  {id:223,ar:"جَسَدِ",tr:"jasadi",fr:"corps",freq:5,cat:"nom"},
  {id:224,ar:"عَيْنِ",tr:"ʿayni",fr:"oeil / source",freq:45,cat:"nom"},
  {id:225,ar:"أُذُنِ",tr:"udhuni",fr:"oreille",freq:6,cat:"nom"},
  {id:226,ar:"لِسَانِ",tr:"lisāni",fr:"langue / parole",freq:25,cat:"nom"},
  {id:227,ar:"يَدِ",tr:"yadi",fr:"main",freq:120,cat:"nom"},
  {id:228,ar:"رِجْلِ",tr:"rijli",fr:"pied / jambe",freq:7,cat:"nom"},
  {id:229,ar:"رَأْسِ",tr:"raʾsi",fr:"tête",freq:10,cat:"nom"},
  {id:230,ar:"قَلْبِ",tr:"qalbi",fr:"cœur",freq:132,cat:"nom"},
  {id:231,ar:"صَدْرِ",tr:"ṣadri",fr:"poitrine / cœur",freq:44,cat:"nom"},
  {id:232,ar:"كَلِمَةَ",tr:"kalimata",fr:"parole / mot",freq:74,cat:"nom"},
  {id:233,ar:"كَلَامَ",tr:"kalāma",fr:"discours / parole",freq:3,cat:"nom"},
  {id:234,ar:"قَوْلَ",tr:"qawla",fr:"parole / propos",freq:61,cat:"nom"},
  {id:235,ar:"فِعْلَ",tr:"fiʿla",fr:"acte / action",freq:2,cat:"nom"},
  {id:236,ar:"عَمَلَ",tr:"ʿamala",fr:"oeuvre / travail",freq:104,cat:"nom"},
  {id:237,ar:"نِيَّةَ",tr:"niyyata",fr:"intention",freq:1,cat:"nom"},
  {id:238,ar:"حِكْمَةَ",tr:"ḥikmata",fr:"sagesse",freq:20,cat:"nom"},
  {id:239,ar:"مَوْعِظَةَ",tr:"mawʿiẓata",fr:"exhortation",freq:5,cat:"nom"},
  {id:240,ar:"فَضِيلَةَ",tr:"faḍīlata",fr:"mérite / vertu",freq:1,cat:"nom"},
  {id:241,ar:"بِرَّ",tr:"birra",fr:"piété / bonté",freq:7,cat:"nom"},
  {id:242,ar:"تَقْوَى",tr:"taqwā",fr:"crainte pieuse",freq:41,cat:"nom"},
  {id:243,ar:"إِخْلَاصَ",tr:"ikhlāṣa",fr:"sincérité",freq:2,cat:"nom"},
  {id:244,ar:"خَشْيَةَ",tr:"khashyata",fr:"crainte / révérence",freq:15,cat:"nom"},
  {id:245,ar:"حُبَّ",tr:"ḥubba",fr:"amour / attachement",freq:23,cat:"nom"},
  {id:246,ar:"كَرَهَ",tr:"karaha",fr:"il déteste / a en horreur",freq:21,cat:"verbe"},
  {id:247,ar:"خَافَ",tr:"khāfa",fr:"il craint",freq:44,cat:"verbe"},
  {id:248,ar:"رَجَا",tr:"rajā",fr:"il espère",freq:28,cat:"verbe"},
  {id:249,ar:"تَابَ",tr:"tāba",fr:"il s'est repenti",freq:88,cat:"verbe"},
  {id:250,ar:"اسْتَغْفَرَ",tr:"istaghfara",fr:"il a demandé pardon",freq:23,cat:"verbe"},
  {id:251,ar:"شَكَرَ",tr:"shakara",fr:"il a remercié",freq:17,cat:"verbe"},
  {id:252,ar:"صَبَرَ",tr:"ṣabara",fr:"il a été patient",freq:45,cat:"verbe"},
  {id:253,ar:"جَاهَدَ",tr:"jāhada",fr:"il a lutté / s'est efforcé",freq:35,cat:"verbe"},
  {id:254,ar:"هَاجَرَ",tr:"hājara",fr:"il a émigré",freq:28,cat:"verbe"},
  {id:255,ar:"نَصَرَ",tr:"naṣara",fr:"il a secouru",freq:27,cat:"verbe"},
  {id:256,ar:"أَعَانَ",tr:"aʿāna",fr:"il a aidé",freq:2,cat:"verbe"},
  {id:257,ar:"أَحَبَّ",tr:"aḥabba",fr:"il a aimé",freq:40,cat:"verbe"},
  {id:258,ar:"غَفَرَ",tr:"ghafara",fr:"il a pardonné",freq:35,cat:"verbe"},
  {id:259,ar:"هَدَى",tr:"hadā",fr:"il a guidé",freq:121,cat:"verbe"},
  {id:260,ar:"عَفَا",tr:"ʿafā",fr:"il a effacé / pardonné",freq:21,cat:"verbe"},
  {id:261,ar:"أَعْطَى",tr:"aʿṭā",fr:"il a donné / accordé",freq:7,cat:"verbe"},
  {id:262,ar:"مَنَعَ",tr:"manaʿa",fr:"il a empêché / refusé",freq:16,cat:"verbe"},
  {id:263,ar:"قَدَّرَ",tr:"qaddara",fr:"il a décrété / mesuré",freq:6,cat:"verbe"},
  {id:264,ar:"دَبَّرَ",tr:"dabbara",fr:"il a dirigé / organisé",freq:4,cat:"verbe"},
  {id:265,ar:"حَاسَبَ",tr:"ḥāsaba",fr:"il a compté / jugé",freq:4,cat:"verbe"},
  {id:266,ar:"جَازَى",tr:"jāzā",fr:"il a rétribué",freq:3,cat:"verbe"},
  {id:267,ar:"عَذَّبَ",tr:"ʿadhdhaba",fr:"il a châtié / torturé",freq:22,cat:"verbe"},
  {id:268,ar:"بَشَّرَ",tr:"bashshara",fr:"il a annoncé bonne nouvelle",freq:15,cat:"verbe"},
  {id:269,ar:"أَنذَرَ",tr:"andhara",fr:"il a averti",freq:54,cat:"verbe"},
  {id:270,ar:"أَقَامَ",tr:"aqāma",fr:"il a établi / accompli",freq:22,cat:"verbe"},
  {id:271,ar:"الصَّلَاةَ",tr:"aṣ-ṣalāh",fr:"la prière rituelle",freq:99,cat:"pilier"},
  {id:272,ar:"رَمَضَانَ",tr:"ramaḍāna",fr:"Ramadan",freq:1,cat:"nom"},
  {id:273,ar:"مَكَّةَ",tr:"makkata",fr:"La Mecque",freq:2,cat:"lieu"},
  {id:274,ar:"الْمَدِينَةَ",tr:"al-madīnata",fr:"Médine / la ville",freq:6,cat:"lieu"},
  {id:275,ar:"الْمَسْجِدَ",tr:"al-masjida",fr:"la mosquée",freq:28,cat:"lieu"},
  {id:276,ar:"الْكَعْبَةَ",tr:"al-kaʿbata",fr:"la Kaaba",freq:2,cat:"lieu"},
  {id:277,ar:"قِبْلَةَ",tr:"qiblata",fr:"direction de prière",freq:4,cat:"nom"},
  {id:278,ar:"الصَّفَا",tr:"aṣ-ṣafā",fr:"As-Safā (colline)",freq:1,cat:"lieu"},
  {id:279,ar:"صِرَاطَ مُسْتَقِيمَ",tr:"ṣirāṭan mustaqīma",fr:"chemin droit",freq:32,cat:"expression"},
  {id:280,ar:"أُولُو الْأَلْبَابِ",tr:"ulū l-albāb",fr:"gens doués de raison",freq:16,cat:"expression"},
  {id:281,ar:"صِدْقِ",tr:"ṣidqi",fr:"véracité / honnêteté",freq:13,cat:"nom"},
  {id:282,ar:"عَدْلِ",tr:"ʿadli",fr:"justice / équité",freq:28,cat:"nom"},
  {id:283,ar:"أَمَانَةَ",tr:"amānata",fr:"confiance / dépôt",freq:6,cat:"nom"},
  {id:284,ar:"شَهَادَةِ",tr:"shahādati",fr:"témoignage",freq:19,cat:"nom"},
  {id:285,ar:"مِيثَاقَ",tr:"mīthāqa",fr:"pacte / alliance",freq:25,cat:"nom"},
  {id:286,ar:"عَهْدَ",tr:"ʿahda",fr:"promesse / engagement",freq:40,cat:"nom"},
  {id:287,ar:"حِلْفَ",tr:"ḥilfa",fr:"serment / alliance",freq:3,cat:"nom"},
  {id:288,ar:"فِتْنَةَ",tr:"fitnata",fr:"épreuve / discorde",freq:60,cat:"nom"},
  {id:289,ar:"بَلَاءَ",tr:"balāʾa",fr:"épreuve / malheur",freq:10,cat:"nom"},
  {id:290,ar:"ذَنْبَ",tr:"dhanba",fr:"péché / faute",freq:43,cat:"nom"},
  {id:291,ar:"خَطَأَ",tr:"khaṭaʾa",fr:"erreur / faute",freq:8,cat:"nom"},
  {id:292,ar:"إِثْمَ",tr:"ithma",fr:"péché / crime",freq:48,cat:"nom"},
  {id:293,ar:"فُجُورَ",tr:"fujūra",fr:"débauche / impiété",freq:5,cat:"nom"},
  {id:294,ar:"كُفْرَ",tr:"kufra",fr:"mécréance",freq:25,cat:"nom"},
  {id:295,ar:"شِرْكَ",tr:"shirka",fr:"association à Allah",freq:28,cat:"nom"},
  {id:296,ar:"نِفَاقَ",tr:"nifāqa",fr:"hypocrisie",freq:3,cat:"nom"},
  {id:297,ar:"بِدْعَةَ",tr:"bidʿata",fr:"innovation blâmable",freq:0,cat:"nom"},
  {id:298,ar:"سُنَّةَ",tr:"sunnata",fr:"voie / tradition",freq:16,cat:"nom"},
  {id:299,ar:"مِلَّةَ",tr:"millata",fr:"religion / communauté",freq:15,cat:"nom"},
  {id:300,ar:"شَرِيعَةَ",tr:"sharīʿata",fr:"loi divine",freq:2,cat:"nom"},
  {id:301,ar:"فِقْهَ",tr:"fiqha",fr:"compréhension / jurisprudence",freq:1,cat:"nom"},
  {id:302,ar:"حَلَالَ",tr:"ḥalāla",fr:"licite / permis",freq:5,cat:"adjectif"},
  {id:303,ar:"حَرَامَ",tr:"ḥarāma",fr:"illicite / interdit",freq:25,cat:"adjectif"},
  {id:304,ar:"طَيِّبَ",tr:"ṭayyiba",fr:"bon / pur / agréable",freq:46,cat:"adjectif"},
  {id:305,ar:"خَبِيثَ",tr:"khabītha",fr:"mauvais / impur",freq:22,cat:"adjectif"},
  {id:306,ar:"قَرِيبَ",tr:"qarība",fr:"proche",freq:24,cat:"adjectif"},
  {id:307,ar:"بَعِيدَ",tr:"baʿīda",fr:"loin / éloigné",freq:17,cat:"adjectif"},
  {id:308,ar:"سَهْلَ",tr:"sahla",fr:"facile / aisé",freq:8,cat:"adjectif"},
  {id:309,ar:"صَعْبَ",tr:"ṣaʿba",fr:"difficile",freq:0,cat:"adjectif"},
  {id:310,ar:"جَدِيدَ",tr:"jadīda",fr:"nouveau",freq:5,cat:"adjectif"},
  {id:311,ar:"قَدِيمَ",tr:"qadīma",fr:"ancien / vieux",freq:0,cat:"adjectif"},
  {id:312,ar:"مُبَارَكَ",tr:"mubāraka",fr:"béni",freq:32,cat:"adjectif"},
  {id:313,ar:"مُقَدَّسَ",tr:"muqaddasa",fr:"sacré / sanctifié",freq:3,cat:"adjectif"},
  {id:314,ar:"عَظِيمَ",tr:"ʿaẓīma",fr:"grand / majestueux",freq:108,cat:"adjectif"},
  {id:315,ar:"كَرِيمَ",tr:"karīma",fr:"généreux / honorable",freq:27,cat:"adjectif"},
  {id:316,ar:"مِنْ قَبْلُ",tr:"min qablu",fr:"avant / auparavant",freq:42,cat:"expression"},
  {id:317,ar:"مِنْ بَعْدُ",tr:"min baʿdu",fr:"après / ensuite",freq:18,cat:"expression"},
  {id:318,ar:"أَوَّلَ",tr:"awwala",fr:"premier",freq:14,cat:"adjectif"},
  {id:319,ar:"آخِرَ",tr:"ākhira",fr:"dernier",freq:19,cat:"adjectif"},
  {id:320,ar:"كُلَّهُ",tr:"kullahu",fr:"tout entier / en totalité",freq:34,cat:"particule"},
  {id:321,ar:"بَعْضُهُمْ",tr:"baʿḍuhum",fr:"certains d'entre eux",freq:58,cat:"pronom"},
  {id:322,ar:"كِلَاهُمَا",tr:"kilāhumā",fr:"les deux",freq:1,cat:"pronom"},
  {id:323,ar:"أَحَدٌ",tr:"aḥadun",fr:"quelqu'un / un seul",freq:79,cat:"pronom"},
  {id:324,ar:"لَا أَحَدَ",tr:"lā aḥada",fr:"personne",freq:0,cat:"expression"},
  {id:325,ar:"شَيْئًا",tr:"shayʾan",fr:"quoi que ce soit",freq:68,cat:"nom"},
  {id:326,ar:"أَبَدًا",tr:"abadan",fr:"jamais / pour toujours",freq:42,cat:"adverbe"},
  {id:327,ar:"دَائِمًا",tr:"dāʾiman",fr:"toujours / en permanence",freq:0,cat:"adverbe"},
  {id:328,ar:"حَقًّا",tr:"ḥaqqan",fr:"vraiment / en vérité",freq:42,cat:"adverbe"},
  {id:329,ar:"يَقِينًا",tr:"yaqīnan",fr:"avec certitude",freq:4,cat:"adverbe"},
  {id:330,ar:"سَرِيعًا",tr:"sarīʿan",fr:"rapidement / vite",freq:18,cat:"adverbe"},
  {id:331,ar:"جَمِيعًا",tr:"jamīʿan",fr:"tous ensemble",freq:120,cat:"adverbe"},
  {id:332,ar:"وَحْدَهُ",tr:"waḥdahu",fr:"seul / lui seul",freq:5,cat:"adverbe"},
  {id:333,ar:"سِرًّا",tr:"sirran",fr:"en secret",freq:14,cat:"adverbe"},
  {id:334,ar:"عَلَانِيَةً",tr:"ʿalāniyatan",fr:"publiquement",freq:6,cat:"adverbe"},
  {id:335,ar:"سَمَاءَ",tr:"samāʾa",fr:"ciel",freq:120,cat:"nom"},
  {id:336,ar:"أَرْضَ",tr:"arḍa",fr:"terre",freq:461,cat:"nom"},
  {id:337,ar:"عَالَمَ",tr:"ʿālama",fr:"monde / univers",freq:73,cat:"nom"},
  {id:338,ar:"خَلِيفَةَ",tr:"khalīfata",fr:"calife / vicaire",freq:9,cat:"nom"},
  {id:339,ar:"أُمَمَ",tr:"umama",fr:"nations / peuples",freq:18,cat:"nom"},
  {id:340,ar:"قَبِيلَةَ",tr:"qabīlata",fr:"tribu",freq:1,cat:"nom"},
  {id:341,ar:"مُلْكَ",tr:"mulka",fr:"royauté / règne",freq:52,cat:"nom"},
  {id:342,ar:"سُلْطَانَ",tr:"sulṭāna",fr:"pouvoir / autorité",freq:37,cat:"nom"},
  {id:343,ar:"حُكُومَةَ",tr:"ḥukūmata",fr:"gouvernement",freq:0,cat:"nom"},
  {id:344,ar:"قَضَاءَ",tr:"qaḍāʾa",fr:"décret / jugement",freq:13,cat:"nom"},
  {id:345,ar:"قَدَرَ",tr:"qadara",fr:"destin / décret divin",freq:6,cat:"nom"},
  {id:346,ar:"لَوْحَ",tr:"lawḥa",fr:"table / tablette",freq:4,cat:"nom"},
  {id:347,ar:"مِيزَانَ",tr:"mīzāna",fr:"balance / mesure",freq:23,cat:"nom"},
  {id:348,ar:"حِسَابَ",tr:"ḥisāba",fr:"calcul / reckoning",freq:29,cat:"nom"},
  {id:349,ar:"صِرَاطَ",tr:"ṣirāṭa",fr:"pont / chemin",freq:45,cat:"nom"},
  {id:350,ar:"أَجَلَ",tr:"ajala",fr:"délai / terme fixé",freq:55,cat:"nom"},
  {id:351,ar:"آدَمَ",tr:"ādama",fr:"Adam",freq:25,cat:"nom propre"},
  {id:352,ar:"نُوحًا",tr:"nūḥan",fr:"Noé",freq:43,cat:"nom propre"},
  {id:353,ar:"يُوسُفَ",tr:"yūsufa",fr:"Joseph",freq:27,cat:"nom propre"},
  {id:354,ar:"دَاوُودَ",tr:"dāwūda",fr:"David",freq:16,cat:"nom propre"},
  {id:355,ar:"سُلَيْمَانَ",tr:"sulaymāna",fr:"Salomon",freq:17,cat:"nom propre"},
  {id:356,ar:"يَحْيَى",tr:"yaḥyā",fr:"Jean (Baptiste)",freq:5,cat:"nom propre"},
  {id:357,ar:"مَرْيَمَ",tr:"maryama",fr:"Marie",freq:34,cat:"nom propre"},
  {id:358,ar:"زَكَرِيَّا",tr:"zakariyyā",fr:"Zacharie",freq:7,cat:"nom propre"},
  {id:359,ar:"لُوطًا",tr:"lūṭan",fr:"Loth",freq:27,cat:"nom propre"},
  {id:360,ar:"إِسْمَاعِيلَ",tr:"ismāʿīla",fr:"Ismaël",freq:12,cat:"nom propre"},
  {id:361,ar:"إِسْحَاقَ",tr:"isḥāqa",fr:"Isaac",freq:17,cat:"nom propre"},
  {id:362,ar:"يَعْقُوبَ",tr:"yaʿqūba",fr:"Jacob",freq:16,cat:"nom propre"},
  {id:363,ar:"أَيُّوبَ",tr:"ayyūba",fr:"Job",freq:4,cat:"nom propre"},
  {id:364,ar:"يُونُسَ",tr:"yūnusa",fr:"Jonas",freq:4,cat:"nom propre"},
  {id:365,ar:"فِرْعَوْنَ",tr:"firʿawna",fr:"Pharaon",freq:74,cat:"nom propre"},
  {id:366,ar:"هَامَانَ",tr:"hāmāna",fr:"Haman",freq:3,cat:"nom propre"},
  {id:367,ar:"قَارُونَ",tr:"qārūna",fr:"Coré",freq:4,cat:"nom propre"},
  {id:368,ar:"بَنِي إِسْرَائِيلَ",tr:"banī isrāʾīl",fr:"Fils d'Israël",freq:40,cat:"expression"},
  {id:369,ar:"أَهْلِ الْكِتَابِ",tr:"ahli l-kitāb",fr:"gens du Livre",freq:30,cat:"expression"},
  {id:370,ar:"الْيَهُودَ",tr:"al-yahūda",fr:"les Juifs",freq:10,cat:"nom"},
  {id:371,ar:"النَّصَارَى",tr:"an-naṣārā",fr:"les Chrétiens",freq:14,cat:"nom"},
  {id:372,ar:"الصَّابِئِينَ",tr:"aṣ-ṣābiʾīna",fr:"les Sabéens",freq:3,cat:"nom"},
  {id:373,ar:"الْمَجُوسَ",tr:"al-majūsa",fr:"les Zoroastriens",freq:1,cat:"nom"},
  {id:374,ar:"أُمَّ الْكِتَابِ",tr:"umma l-kitāb",fr:"mère du Livre",freq:3,cat:"expression"},
  {id:375,ar:"مَلَكُوتَ",tr:"malakūta",fr:"royauté céleste",freq:3,cat:"nom"},
  {id:376,ar:"الْعَرْشَ",tr:"al-ʿarsha",fr:"le Trône",freq:33,cat:"nom"},
  {id:377,ar:"الْكُرْسِيَّ",tr:"al-kursiyya",fr:"le Siège / Trône",freq:2,cat:"nom"},
  {id:378,ar:"اللَّوْحَ الْمَحْفُوظَ",tr:"al-lawḥa l-maḥfūẓ",fr:"la Table gardée",freq:1,cat:"expression"},
  {id:379,ar:"الْقَلَمَ",tr:"al-qalama",fr:"le calame / la plume",freq:4,cat:"nom"},
  {id:380,ar:"وَحْيَ",tr:"waḥya",fr:"révélation",freq:26,cat:"nom"},
  {id:381,ar:"تَنزِيلَ",tr:"tanzīla",fr:"révélation descendue",freq:14,cat:"nom"},
  {id:382,ar:"مُعْجِزَةَ",tr:"muʿjizata",fr:"miracle",freq:0,cat:"nom"},
  {id:383,ar:"حُجَّةَ",tr:"ḥujjata",fr:"argument / preuve",freq:7,cat:"nom"},
  {id:384,ar:"بَيِّنَةَ",tr:"bayyinata",fr:"preuve évidente",freq:19,cat:"nom"},
  {id:385,ar:"دَلِيلَ",tr:"dalīla",fr:"preuve / indice",freq:0,cat:"nom"},
  {id:386,ar:"فَجْرَ",tr:"fajra",fr:"aurore / aube",freq:12,cat:"nom"},
  {id:387,ar:"ضُحَى",tr:"ḍuḥā",fr:"matin lumineux",freq:4,cat:"nom"},
  {id:388,ar:"الظُّهْرَ",tr:"aẓ-ẓuhr",fr:"midi",freq:1,cat:"nom"},
  {id:389,ar:"الْعَصْرَ",tr:"al-ʿaṣr",fr:"l'après-midi / le temps",freq:2,cat:"nom"},
  {id:390,ar:"الْمَغْرِبَ",tr:"al-maghrib",fr:"coucher du soleil",freq:3,cat:"nom"},
  {id:391,ar:"الْعِشَاءَ",tr:"al-ʿishāʾa",fr:"le soir / nuit tombée",freq:2,cat:"nom"},
  {id:392,ar:"سَحَرًا",tr:"saḥaran",fr:"au moment du sahour",freq:2,cat:"nom"},
  {id:393,ar:"غَدًا",tr:"ghadan",fr:"demain",freq:3,cat:"adverbe"},
  {id:394,ar:"أَمْسِ",tr:"amsi",fr:"hier",freq:2,cat:"adverbe"},
  {id:395,ar:"الْيَوْمَ",tr:"al-yawma",fr:"aujourd'hui",freq:44,cat:"adverbe"},
  {id:396,ar:"مُقِيمًا",tr:"muqīman",fr:"demeurant / résidant",freq:9,cat:"adjectif"},
  {id:397,ar:"مُهَاجِرًا",tr:"muhājiran",fr:"émigrant",freq:4,cat:"nom"},
  {id:398,ar:"مُجَاهِدًا",tr:"mujāhidan",fr:"combattant sur la voie d'Allah",freq:2,cat:"nom"},
  {id:399,ar:"عَابِدًا",tr:"ʿābidan",fr:"adorateur",freq:4,cat:"nom"},
  {id:400,ar:"ذَاكِرًا",tr:"dhākiran",fr:"celui qui se rappelle",freq:1,cat:"nom"},
  {id:401,ar:"تَوَكَّلَ",tr:"tawakkala",fr:"il s'est confié à Allah",freq:14,cat:"verbe"},
  {id:402,ar:"اسْتَعَانَ",tr:"istaʿāna",fr:"il a imploré le secours",freq:3,cat:"verbe"},
  {id:403,ar:"خَضَعَ",tr:"khaḍaʿa",fr:"il s'est soumis",freq:3,cat:"verbe"},
  {id:404,ar:"أَسْلَمَ",tr:"aslama",fr:"il s'est soumis / converti",freq:9,cat:"verbe"},
  {id:405,ar:"آمَنَ",tr:"āmana",fr:"il a cru / a la foi",freq:258,cat:"verbe"},
  {id:406,ar:"اتَّقَى",tr:"ittaqā",fr:"il a été pieux / craint Allah",freq:43,cat:"verbe"},
  {id:407,ar:"رَضِيَ",tr:"raḍiya",fr:"il a agréé / été satisfait",freq:25,cat:"verbe"},
  {id:408,ar:"أَسَاءَ",tr:"asāʾa",fr:"il a mal agi",freq:4,cat:"verbe"},
  {id:409,ar:"أَصْلَحَ",tr:"aṣlaḥa",fr:"il a réformé / amélioré",freq:36,cat:"verbe"},
  {id:410,ar:"أَفْسَدَ",tr:"afsada",fr:"il a corrompu",freq:25,cat:"verbe"},
  {id:411,ar:"كَذَبَ",tr:"kadhaba",fr:"il a menti",freq:88,cat:"verbe"},
  {id:412,ar:"صَدَقَ",tr:"ṣadaqa",fr:"il a dit la vérité",freq:18,cat:"verbe"},
  {id:413,ar:"وَعَدَ",tr:"waʿada",fr:"il a promis",freq:55,cat:"verbe"},
  {id:414,ar:"خَانَ",tr:"khāna",fr:"il a trahi",freq:14,cat:"verbe"},
  {id:415,ar:"حَكَمَ",tr:"ḥakama",fr:"il a jugé / rendu un verdict",freq:72,cat:"verbe"},
  {id:416,ar:"شَهِدَ",tr:"shahida",fr:"il a témoigné",freq:39,cat:"verbe"},
  {id:417,ar:"أَنْفَقَ",tr:"anfaqa",fr:"il a dépensé / donné",freq:61,cat:"verbe"},
  {id:418,ar:"بَخِلَ",tr:"bakhila",fr:"il a été avare",freq:7,cat:"verbe"},
  {id:419,ar:"أَكَلَ",tr:"akala",fr:"il a mangé",freq:27,cat:"verbe"},
  {id:420,ar:"شَرِبَ",tr:"shariba",fr:"il a bu",freq:9,cat:"verbe"},
  {id:421,ar:"نَامَ",tr:"nāma",fr:"il a dormi",freq:5,cat:"verbe"},
  {id:422,ar:"قَامَ",tr:"qāma",fr:"il s'est levé / s'est établi",freq:49,cat:"verbe"},
  {id:423,ar:"جَلَسَ",tr:"jalasa",fr:"il s'est assis",freq:2,cat:"verbe"},
  {id:424,ar:"مَشَى",tr:"mashā",fr:"il a marché",freq:11,cat:"verbe"},
  {id:425,ar:"رَكَعَ",tr:"rakaʿa",fr:"il s'est incliné",freq:13,cat:"verbe"},
  {id:426,ar:"سَجَدَ",tr:"sajada",fr:"il s'est prosterné",freq:22,cat:"verbe"},
  {id:427,ar:"دَخَلَ",tr:"dakhala",fr:"il est entré",freq:89,cat:"verbe"},
  {id:428,ar:"خَرَجَ",tr:"kharaja",fr:"il est sorti",freq:55,cat:"verbe"},
  {id:429,ar:"ذَهَبَ",tr:"dhahaba",fr:"il est parti / allé",freq:33,cat:"verbe"},
  {id:430,ar:"جَاءَ",tr:"jāʾa",fr:"il est venu / arrivé",freq:278,cat:"verbe"},
  {id:431,ar:"رَجَعَ",tr:"rajaʿa",fr:"il est revenu / retourné",freq:91,cat:"verbe"},
  {id:432,ar:"وَقَفَ",tr:"waqafa",fr:"il s'est arrêté",freq:6,cat:"verbe"},
  {id:433,ar:"رَأَى",tr:"raʾā",fr:"il a vu",freq:113,cat:"verbe"},
  {id:434,ar:"سَأَلَ",tr:"saʾala",fr:"il a demandé",freq:63,cat:"verbe"},
  {id:435,ar:"أَجَابَ",tr:"ajāba",fr:"il a répondu",freq:6,cat:"verbe"},
  {id:436,ar:"أَمَرَ",tr:"amara",fr:"il a ordonné",freq:91,cat:"verbe"},
  {id:437,ar:"نَهَى",tr:"nahā",fr:"il a interdit / défendu",freq:27,cat:"verbe"},
  {id:438,ar:"نَسِيَ",tr:"nasiya",fr:"il a oublié",freq:26,cat:"verbe"},
  {id:439,ar:"تَذَكَّرَ",tr:"tadhakkara",fr:"il s'est souvenu",freq:15,cat:"verbe"},
  {id:440,ar:"فَكَّرَ",tr:"fakkara",fr:"il a réfléchi",freq:4,cat:"verbe"},
  {id:441,ar:"فَهِمَ",tr:"fahima",fr:"il a compris",freq:2,cat:"verbe"},
  {id:442,ar:"عَرَفَ",tr:"ʿarafa",fr:"il a reconnu / connu",freq:19,cat:"verbe"},
  {id:443,ar:"جَهِلَ",tr:"jahila",fr:"il a ignoré",freq:8,cat:"verbe"},
  {id:444,ar:"اهْتَدَى",tr:"ihtadā",fr:"il s'est guidé / suivi la voie",freq:46,cat:"verbe"},
  {id:445,ar:"ضَلَّ",tr:"ḍalla",fr:"il s'est égaré",freq:56,cat:"verbe"},
  {id:446,ar:"تَابَ",tr:"tāba",fr:"il s'est repenti",freq:88,cat:"verbe"},
  {id:447,ar:"فَازَ",tr:"fāza",fr:"il a réussi / triomphé",freq:22,cat:"verbe"},
  {id:448,ar:"خَسِرَ",tr:"khasira",fr:"il a perdu",freq:38,cat:"verbe"},
  {id:449,ar:"نَجَا",tr:"najā",fr:"il a été sauvé",freq:16,cat:"verbe"},
  {id:450,ar:"هَلَكَ",tr:"halaka",fr:"il a péri",freq:17,cat:"verbe"},
  {id:451,ar:"نَعَمْ",tr:"naʿam",fr:"oui / certainement",freq:2,cat:"particule"},
  {id:452,ar:"لِمَاذَا",tr:"limādhā",fr:"pourquoi",freq:0,cat:"particule"},
  {id:453,ar:"أَيْنَ",tr:"ayna",fr:"où",freq:24,cat:"particule"},
  {id:454,ar:"مَتَى",tr:"matā",fr:"quand",freq:8,cat:"particule"},
  {id:455,ar:"كَمْ",tr:"kam",fr:"combien",freq:11,cat:"particule"},
  {id:456,ar:"أَيُّ",tr:"ayyu",fr:"quel / lequel",freq:25,cat:"particule"},
  {id:457,ar:"مَاذَا",tr:"mādhā",fr:"que / quoi",freq:17,cat:"particule"},
  {id:458,ar:"لِمَنْ",tr:"liman",fr:"à qui / pour qui",freq:12,cat:"particule"},
  {id:459,ar:"عَمَّ",tr:"ʿamma",fr:"de quoi / au sujet de",freq:4,cat:"particule"},
  {id:460,ar:"لِكَيْ",tr:"likay",fr:"afin que / pour que",freq:8,cat:"particule"},
  {id:461,ar:"كَأَنَّ",tr:"kaʾanna",fr:"comme si",freq:9,cat:"particule"},
  {id:462,ar:"مِثْلَ",tr:"mithla",fr:"comme / semblable à",freq:53,cat:"particule"},
  {id:463,ar:"غَيْرَ",tr:"ghayra",fr:"autre que / non",freq:115,cat:"particule"},
  {id:464,ar:"سِوَى",tr:"siwā",fr:"excepté / en dehors de",freq:4,cat:"particule"},
  {id:465,ar:"دُونَ",tr:"dūna",fr:"sans / en dehors de",freq:74,cat:"particule"},
  {id:466,ar:"نَحْوَ",tr:"naḥwa",fr:"vers / en direction de",freq:0,cat:"préposition"},
  {id:467,ar:"حَوْلَ",tr:"ḥawla",fr:"autour de",freq:17,cat:"préposition"},
  {id:468,ar:"خِلَالَ",tr:"khilāla",fr:"à travers / pendant",freq:4,cat:"préposition"},
  {id:469,ar:"بِدُونِ",tr:"bidūni",fr:"sans",freq:0,cat:"préposition"},
  {id:470,ar:"مُنْذُ",tr:"mundhu",fr:"depuis / il y a",freq:0,cat:"préposition"},
  {id:471,ar:"زَوْجَ",tr:"zawja",fr:"époux / épouse",freq:82,cat:"nom"},
  {id:472,ar:"أُمَّ",tr:"umma",fr:"mère",freq:35,cat:"nom"},
  {id:473,ar:"أَخَ",tr:"akha",fr:"frère",freq:94,cat:"nom"},
  {id:474,ar:"أُخْتَ",tr:"ukhta",fr:"sœur",freq:13,cat:"nom"},
  {id:475,ar:"ابْنَ",tr:"ibna",fr:"fils",freq:162,cat:"nom"},
  {id:476,ar:"بِنْتَ",tr:"binta",fr:"fille",freq:3,cat:"nom"},
  {id:477,ar:"جَدَّ",tr:"jadda",fr:"grand-père",freq:0,cat:"nom"},
  {id:478,ar:"عَمَّ",tr:"ʿamma",fr:"oncle paternel",freq:1,cat:"nom"},
  {id:479,ar:"خَالَ",tr:"khāla",fr:"oncle maternel",freq:0,cat:"nom"},
  {id:480,ar:"صَدِيقَ",tr:"ṣadīqa",fr:"ami / proche",freq:4,cat:"nom"},
  {id:481,ar:"عَدُوَّ",tr:"ʿaduwwa",fr:"ennemi",freq:78,cat:"nom"},
  {id:482,ar:"جَارَ",tr:"jāra",fr:"voisin",freq:1,cat:"nom"},
  {id:483,ar:"ضَيْفَ",tr:"ḍayfa",fr:"invité / hôte",freq:4,cat:"nom"},
  {id:484,ar:"يَتِيمَ",tr:"yatīma",fr:"orphelin",freq:22,cat:"nom"},
  {id:485,ar:"مِسْكِينَ",tr:"miskīna",fr:"pauvre / indigent",freq:23,cat:"nom"},
  {id:486,ar:"أَسِيرَ",tr:"asīra",fr:"prisonnier / captif",freq:4,cat:"nom"},
  {id:487,ar:"غَرِيبَ",tr:"gharība",fr:"étranger",freq:0,cat:"nom"},
  {id:488,ar:"ظَالِمَ",tr:"ẓālima",fr:"oppresseur",freq:94,cat:"nom"},
  {id:489,ar:"مَظْلُومَ",tr:"maẓlūma",fr:"opprimé",freq:5,cat:"nom"},
  {id:490,ar:"حَاكِمَ",tr:"ḥākima",fr:"gouvernant / juge",freq:6,cat:"nom"},
  {id:491,ar:"رَاعِيَ",tr:"rāʿiya",fr:"berger / gardien",freq:0,cat:"nom"},
  {id:492,ar:"طَالِبَ",tr:"ṭāliba",fr:"étudiant / demandeur",freq:0,cat:"nom"},
  {id:493,ar:"مُعَلِّمَ",tr:"muʿallima",fr:"enseignant",freq:0,cat:"nom"},
  {id:494,ar:"عَالِمَ",tr:"ʿālima",fr:"savant / érudit",freq:8,cat:"nom"},
  {id:495,ar:"طَبِيبَ",tr:"ṭabība",fr:"médecin",freq:0,cat:"nom"},
  {id:496,ar:"إِنَّا لِلَّهِ",tr:"innā lillāh",fr:"Certes nous appartenons à Allah",freq:1,cat:"expression"},
  {id:497,ar:"مَا شَاءَ اللَّهُ",tr:"mā shāʾa llāh",fr:"Ce qu'Allah a voulu",freq:2,cat:"expression"},
  {id:498,ar:"جَزَاكَ اللَّهُ",tr:"jazāka llāh",fr:"Qu'Allah te récompense",freq:0,cat:"expression"},
  {id:499,ar:"أَعُوذُ بِاللَّهِ",tr:"aʿūdhu billāh",fr:"Je cherche refuge en Allah",freq:3,cat:"expression"},
  {id:500,ar:"صَلَّى اللَّهُ عَلَيْهِ",tr:"ṣallā llāhu ʿalayhi",fr:"Que la paix d'Allah soit sur lui",freq:0,cat:"expression"},
];

// ═══════════════════════════════════════════════════════

export default VOCAB;
